### PR TITLE
maint: Drop node 14

### PR DESCRIPTION
**Pull request by tux3**

### CODE REVIEW

**Comment by tux3** [comment]
CI seems to be misteriously broken with the karma install :/

**Comment by tux3** [comment]
We were somehow pointing to a dangling commit.. suspect they may have rebased or git-filter-branch'd a public branch... :|

**Review by JMounier — APPROVED** [review]
Can you add Node 20 to the test matrix?

**Comment by tux3** [comment]
> Can you add Node 20 to the test matrix?

Already done :P

**Pull request merged**
